<?php
 
namespace portpontrieuxBundle\Repository;
 
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
 
/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{
           
            public function mesEmplacementsDQL($em)
            {
                        $req = $em->createQuery('SELECT e FROM PortPontrieuxBundle:Emplacement e');
                        $resultats = $req->getResult();
                       
                        return $resultats;
            }
           
            public function mesEmplacementsQueryBuilder($page, $nbParPage)
            {
                        /*
                        // Méthode 1 : en passant par l'EntityManager
                        $queryBuilder = $this->_em->createQueryBuilder()
                          ->select('e')
                          ->from($this->_entityName, 'e');
                        */
                       
                        // Méthode 2 : en passant par le raccourci (préférable)
                        $queryBuilder = $this->createQueryBuilder('e');
                        // On récupère la Query à partir du QueryBuilder
                        $query = $queryBuilder->getQuery();
                       
					    // On gère ensuite la pagination grace au service Paginator qui nous fournit
                        // entre autres les méthodes setFirstResult et setMaxResults
                        $query
                          // On définit l'emplacement à partir duqel commencer la liste
                          ->setFirstResult(($page-1) * $nbParPage)
                          // Ainsi que le nombre de formations à afficher sur une page
                          ->setMaxResults($nbParPage)
                        ;
                       
                        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
                        return new Paginator($query, true);
            }
}