<?php

namespace portpontrieuxBundle\Repository;

/**
 * LouerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LouerRepository extends \Doctrine\ORM\EntityRepository
{
}
